version: "3.8"

services:
  frontend_test:
    image: vidly-docker-compose-frontend
    depends_on: 
      - backend
    volumes:
      - ./frontend:/app
    command: npm test
  
  frontend:
    depends_on: 
      - backend
    build: ./frontend
    ports:
      - 3000:3000
    environment: 
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app

  backend_test:
    image: vidly-docker-compose-backend
    depends_on: 
      - db
    environment: 
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    command: npm test

  backend: 
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 3001:3001
    environment: 
      DB_URL: mongodb://db/vidly
    volumes: 
      - ./backend:/app
    command: ./docker-entrypoint.sh

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:

